### PR TITLE
Stream context.dataDir to Docker at build-time

### PR DESCRIPTION
**Pull request by logankoester**
Creating an archive on disk for `strider-docker-build` during the **Prepare** phase doesn't work for images that want to include build output or other files generated by Strider in an earlier phase.

This change replaces `git archive` with the [tar-fs](https://www.npmjs.com/package/tar-fs) module to stream project files directly into Docker when building the image instead.

This also resolves the phase conflict that occurs when attempting to build a Docker image during **Prepare**, and there are no more archive files soaking up `/tmp` space.

_See #10 (Why work out of archive path?) if you are interested in the specific use case that motivated this._

_Note that this branch is based off #5 (Push after build) when merging._

### CODE REVIEW

**Comment by logankoester** [comment]
@knownasilya Done!

**Comment by logankoester** [comment]
Hey @knownasilya, any particular issue still blocking this change from being merged?

**Comment by knownasilya** [comment]
Nothing! I missed that you rebased it.

**Comment by logankoester** [comment]
Awesome, thank you!

**Comment by knownasilya** [comment]
Deployed

**Pull request merged**
